backend:
  name: github
  repo: zachauten/website
  branch: main
  # For local development, change base_url to: http://localhost:8788
  # For production, use: https://website.zachauten.workers.dev/
  base_url: https://website.zachauten.workers.dev/

  auth_endpoint: /api/auth
media_folder: public/images
public_folder: /public/images

collections:
  - name: "post"
    label: "Post"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }